name: CI/CD for Kit_It_project_db

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Työ SQL-tiedostojen yhdistämiseen
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Lint SQL files
        run: |
          sqlfluff lint sql/*.sql --dialect postgres
        # Poista seuraavan rivin kommentit nukkaamisen vahvistamiseksi
        # jatka virhettä: epätosi

  # Tietokannan määrittäminen ja siirtojen suorittaminen
  run-migrations:
    runs-on: ubuntu-latest
    needs: lint-sql  # Varmistaa, että nukkaaminen läpäisee ennen siirtoja
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PostgreSQL
        uses: postgres-actions/setup-postgres@v2
        with:
          postgres-version: 15
          database: kit_it_db
          username: postgres
          password: admin

      - name: Run migrations
        run: |
          psql -h localhost -U postgres -d kit_it_db -f sql/create_tables.sql
          psql -h localhost -U postgres -d kit_it_db -f sql/insert_data.sql

  # Käyttöönottotyö (esimerkki)
  deploy:
    runs-on: ubuntu-latest
    needs: run-migrations  # Varmistaa, että siirrot onnistuvat ennen käyttöönottoa
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deployment process starts here."
          # Add deployment commands here
